nginx:
  replicaCount: 1
  image:
    repository: nginx
    tag: latest
  env:
    DB_HOST: "postgres-service"
    DB_PORT: "5432"
    DB_USER: "user"
    DB_PASSWORD: "password"
  configMapName: nginx-html
  service:
    type: LoadBalancer
    port: 80

postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: latest
  env:
    POSTGRES_DB: "mydatabase"
    POSTGRES_USER: "user"
    POSTGRES_PASSWORD: "password"
  pvc:
    storage: 3Gi
  pv:
    storage: 3Gi
  service:
    port: 5432

