apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.configMapName }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>My Custom Nginx Page</title>
        <link rel="stylesheet" type="text/css" href="styles.css">
    </head>
    <body>
        <h1>Hello, Kubernetes!</h1>
    </body>
    </html>
  styles.css: |
    body {
        font-family: Arial, sans-serif;
        background-color: #f0f0f0;
        text-align: center;
        padding: 50px;
    }
    h1 {
        color: #333;
    }
