apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: {{ .Values.nginx.service.port }}
    targetPort: 80
  type: {{ .Values.nginx.service.type }}
